/* Family Quest v0.23.8 — monthly bill fields + Admin subtabs + profile header controls */
(function(){
state.adminCatalogTab0238=state.adminCatalogTab0238||'chores';state.adminChoreSubtab0238=state.adminChoreSubtab0238||'Daily';state.adminAchievementSubtab0238=state.adminAchievementSubtab0238||'Visible';
const oldLoad=window.FQLoaders?.chores;
async function load0238(){if(!(window.FQAuth?.realSession&&window.FQAuth?.profile?.household_id))return;if(oldLoad)await oldLoad();const c=window.FQAuth.client,p=window.FQAuth.profile,{data,error}=await c.from('chore_definitions').select('id,amount_due_cents,amount_due_note').eq('household_id',p.household_id);if(error)return;const m=new Map((data||[]).map(x=>[String(x.id),x]));(state.chores||[]).forEach(x=>{const z=m.get(String(x.definitionId||x.id));x.amountDueCents=z?.amount_due_cents??null;x.amountDueNote=z?.amount_due_note||''})}
if(window.FQLoaders){window.FQLoaders.chores=load0238;loadRealChores=load0238}
const oldCard=choreCard;choreCard=function(c){let h=oldCard(c);if(c.type==='Monthly'&&c.amountDueCents!=null){const box=`<div class="bill-due-box"><span>💵 AMOUNT DUE</span><strong>$${(c.amountDueCents/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</strong>${c.amountDueNote?`<small>${esc(c.amountDueNote)}</small>`:''}</div>`;h=h.replace('<div class="quest-meta">',box+'<div class="quest-meta">')}return h};
const oldEdit=openAdminEditor;openAdminEditor=function(type,id=null){oldEdit(type,id);if(type!=='chore')return;const o=id?state.chores.find(x=>String(x.id)===String(id)):null,ts=$('#aeType'),body=$('#adminEditorBody .form-grid');if(!body||$('#aeAmountDue'))return;body.insertAdjacentHTML('beforeend',`<div class="full monthly-bill-fields"><h4>💵 Monthly Bill Details <span class="muted">(optional)</span></h4><div class="grid two"><label>Amount Due ($)<input id="aeAmountDue" type="number" min="0" step="0.01" placeholder="e.g. 1250.00" value="${o?.amountDueCents!=null?(o.amountDueCents/100).toFixed(2):''}"></label><label>Amount Note<input id="aeAmountNote" placeholder="e.g. Rent, Electric, Minimum payment" value="${esc(o?.amountDueNote||'')}"></label></div></div>`);const show=()=>{$('.monthly-bill-fields').hidden=ts?.value!=='Monthly'};ts?.addEventListener('change',show);show()};
$('#adminEditorForm')?.addEventListener('submit',async e=>{if(state.editing?.type!=='chore'||!realChoresEnabled())return;e.preventDefault();e.stopImmediatePropagation();const o=state.editing.id?state.chores.find(x=>String(x.id)===String(state.editing.id)):null,t=$('#aeType').value,ids=[...document.querySelectorAll('input[name="aeAssignees"]:checked')].map(x=>x.value),due=(t==='Monthly'||t==='One-Off')?($('#aeDue').value||null):null,amt=t==='Monthly'&&$('#aeAmountDue')?.value!==''?Math.round(+$('#aeAmountDue').value*100):null;const {error}=await window.FQAuth.client.rpc('save_chore_definition_v0238',{p_id:o?.definitionId||o?.id||null,p_title:$('#aeTitle').value.trim(),p_category:o?.category||'Other',p_frequency:frequencyValue(t),p_assigned_user_ids:ids,p_xp:+$('#aeXp').value,p_bounty_cents:Math.round(+($('#aeBounty').value||0)*100),p_due_at:due,p_expectations:$('#aeDetails').value.split('\n').map(x=>x.trim()).filter(Boolean),p_active:o?.active!==false,p_allow_multiple:$('#aeMultiple').value==='true',p_failure_penalty_rp:+($('#aePenalty').value||0),p_amount_due_cents:amt,p_amount_due_note:t==='Monthly'?($('#aeAmountNote')?.value||null):null});if(error){toast(error.message);return}$('#adminEditor').close();toast('Chore saved.');await load0238();render()},true);
function adminTabs(){if(state.view!=='admin')return;const card=[...view.querySelectorAll('.card')].find(c=>c.querySelector('h3')?.textContent?.trim()==='Chores');if(!card)return;const headings=[...card.querySelectorAll(':scope > h3')];const findH=n=>headings.find(h=>h.textContent.trim()===n);const groups={chores:findH('Chores'),rewards:findH('Rewards'),achievements:findH('Achievements')};const top=card.querySelector('.admin-tabs-0236')||card.querySelector('.admin-catalog-tabs');if(top){top.innerHTML=`${[['chores','⚔️ Chores'],['rewards','🎁 Rewards'],['achievements','🏆 Achievements'],['cosmetics','🎨 Cosmetic Pricing']].map(([id,l])=>`<button class="ghost ${state.adminCatalogTab0238===id?'active':''}" data-admin-main-0238="${id}">${l}</button>`).join('')}`}
const pricing=[...view.querySelectorAll('.card')].find(c=>/Cosmetic Shop Pricing/i.test(c.textContent||''));if(pricing)pricing.hidden=state.adminCatalogTab0238!=='cosmetics';Object.entries(groups).forEach(([k,h])=>{if(!h)return;h.hidden=k!==state.adminCatalogTab0238;let n=h.nextElementSibling;while(n&&!['H3'].includes(n.tagName)){n.hidden=k!==state.adminCatalogTab0238;n=n.nextElementSibling}});
if(state.adminCatalogTab0238==='chores'&&groups.chores){const h=groups.chores,sub=document.createElement('div');sub.className='tabs admin-subtabs-0238';sub.innerHTML=['Daily','Weekly','Monthly','Seasonal'].map(x=>`<button class="ghost ${state.adminChoreSubtab0238===x?'active':''}" data-admin-chore-sub-0238="${x}">${x}</button>`).join('');h.after(sub);let list=sub.nextElementSibling;while(list&&list.tagName!=='H3'){if(list.matches?.('.simple-list,.admin-list,.quest-list'))[...list.children].forEach(row=>{const txt=row.textContent||'';row.hidden=!txt.toLowerCase().includes(state.adminChoreSubtab0238.toLowerCase())});list=list.nextElementSibling}}
if(state.adminCatalogTab0238==='achievements'&&groups.achievements){const h=groups.achievements,sub=document.createElement('div');sub.className='tabs admin-subtabs-0238';sub.innerHTML=['Visible','Secret'].map(x=>`<button class="ghost ${state.adminAchievementSubtab0238===x?'active':''}" data-admin-ach-sub-0238="${x}">${x}</button>`).join('');h.after(sub);let list=sub.nextElementSibling;while(list&&list.tagName!=='H3'){if(list.matches?.('.simple-list,.admin-list,.achievement-list'))[...list.children].forEach(row=>{const txt=(row.textContent||'').toLowerCase(),secret=txt.includes('secret');row.hidden=state.adminAchievementSubtab0238==='Secret'?!secret:secret});list=list.nextElementSibling}}
}
const oldRender=render;render=function(){oldRender();setTimeout(adminTabs,0)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.adminMain0238){e.preventDefault();e.stopImmediatePropagation();state.adminCatalogTab0238=b.dataset.adminMain0238;render()}else if(b.dataset.adminChoreSub0238){e.preventDefault();e.stopImmediatePropagation();state.adminChoreSubtab0238=b.dataset.adminChoreSub0238;render()}else if(b.dataset.adminAchSub0238){e.preventDefault();e.stopImmediatePropagation();state.adminAchievementSubtab0238=b.dataset.adminAchSub0238;render()}},true);
function profileControls(){const hero=view.querySelector('.profile-page-hero');if(!hero)return;const back=hero.querySelector('[data-action="profile-back"]'),custom=hero.querySelector('[data-action="profile-open"]'),name=hero.querySelector('h2');if(!name||(!back&&!custom))return;let bar=hero.querySelector('.profile-title-control-row');if(!bar){bar=document.createElement('div');bar.className='profile-title-control-row';name.parentElement.insertBefore(bar,name);bar.append(back||document.createElement('span'));bar.append(name);bar.append(custom||document.createElement('span'))}}
const obs=new MutationObserver(()=>{if(state.view==='profiles')profileControls()});obs.observe(view,{childList:true,subtree:true});
})();