/* Family Quest v0.23.8 — monthly bill fields + Admin subtabs + profile header controls */
(function(){
state.adminCatalogTab0238=state.adminCatalogTab0238||'chore';state.adminChoreSubtab0238=state.adminChoreSubtab0238||'Daily';state.adminAchievementSubtab0238=state.adminAchievementSubtab0238||'Visible';
function badge(){const b=document.getElementById('buildBadge');if(b&&b.textContent!=='v0.23.8')b.textContent='v0.23.8'}
const oldLoad=window.FQLoaders?.chores;async function load0238(){if(oldLoad)await oldLoad();if(!(window.FQAuth?.realSession&&window.FQAuth?.profile?.household_id))return;const {data}=await window.FQAuth.client.from('chore_definitions').select('id,amount_due_cents,amount_due_note').eq('household_id',window.FQAuth.profile.household_id);const m=new Map((data||[]).map(x=>[String(x.id),x]));(state.chores||[]).forEach(x=>{const z=m.get(String(x.definitionId||x.id));x.amountDueCents=z?.amount_due_cents??null;x.amountDueNote=z?.amount_due_note||''})}if(window.FQLoaders){window.FQLoaders.chores=load0238;loadRealChores=load0238}
const oldCard=choreCard;choreCard=function(c){let h=oldCard(c);if(c.type==='Monthly'&&c.amountDueCents!=null){const box=`<div class="bill-due-box"><span>💵 AMOUNT DUE</span><strong>$${(c.amountDueCents/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</strong>${c.amountDueNote?`<small>${esc(c.amountDueNote)}</small>`:''}</div>`;h=h.replace('<div class="quest-meta">',box+'<div class="quest-meta">')}return h};
const oldEdit=openAdminEditor;openAdminEditor=function(type,id=null){oldEdit(type,id);if(type!=='chore')return;const o=id?state.chores.find(x=>String(x.id)===String(id)):null,ts=$('#aeType'),body=$('#adminEditorBody .form-grid');if(!body||$('#aeAmountDue'))return;body.insertAdjacentHTML('beforeend',`<div class="full monthly-bill-fields"><h4>💵 Monthly Bill Details <span class="muted">(optional)</span></h4><div class="grid two"><label>Amount Due ($)<input id="aeAmountDue" type="number" min="0" step="0.01" placeholder="e.g. 1250.00" value="${o?.amountDueCents!=null?(o.amountDueCents/100).toFixed(2):''}"></label><label>Amount Note<input id="aeAmountNote" placeholder="e.g. Rent, Electric, Minimum payment" value="${esc(o?.amountDueNote||'')}"></label></div></div>`);const show=()=>{$('.monthly-bill-fields').hidden=ts?.value!=='Monthly'};ts?.addEventListener('change',show);show()};
$('#adminEditorForm')?.addEventListener('submit',async e=>{if(state.editing?.type!=='chore'||!realChoresEnabled())return;e.preventDefault();e.stopImmediatePropagation();const o=state.editing.id?state.chores.find(x=>String(x.id)===String(state.editing.id)):null,t=$('#aeType').value,ids=[...document.querySelectorAll('input[name="aeAssignees"]:checked')].map(x=>x.value),due=(t==='Monthly'||t==='One-Off')?($('#aeDue').value||null):null,amt=t==='Monthly'&&$('#aeAmountDue')?.value!==''?Math.round(+$('#aeAmountDue').value*100):null;const {error}=await window.FQAuth.client.rpc('save_chore_definition_v0238',{p_id:o?.definitionId||o?.id||null,p_title:$('#aeTitle').value.trim(),p_category:o?.category||'Other',p_frequency:frequencyValue(t),p_assigned_user_ids:ids,p_xp:+$('#aeXp').value,p_bounty_cents:Math.round(+($('#aeBounty').value||0)*100),p_due_at:due,p_expectations:$('#aeDetails').value.split('\n').map(x=>x.trim()).filter(Boolean),p_active:o?.active!==false,p_allow_multiple:$('#aeMultiple').value==='true',p_failure_penalty_rp:+($('#aePenalty').value||0),p_amount_due_cents:amt,p_amount_due_note:t==='Monthly'?($('#aeAmountNote')?.value||null):null});if(error){toast(error.message);return}$('#adminEditor').close();toast('Chore saved.');await load0238();render()},true);
function sectionLabel(s){return s?.querySelector('h3')?.textContent?.trim()||''}
function adminTabs(){badge();if(state.view!=='admin')return;const root=document.getElementById('view');const management=[...root.querySelectorAll('.card')].find(c=>{const ls=[...c.querySelectorAll('.section-title')].map(sectionLabel);return ls.includes('Chores')&&ls.includes('Rewards')&&ls.includes('Achievements')});if(!management)return;
management.querySelectorAll('.admin-catalog-tabs-v236,.admin-catalog-tabs:not(.admin-catalog-tabs-v238)').forEach(x=>x.remove());let top=management.querySelector('.admin-catalog-tabs-v238');if(!top){top=document.createElement('div');top.className='tabs admin-catalog-tabs-v238';management.prepend(top)}top.innerHTML=[['chore','⚔️ Chores'],['reward','🎁 Rewards'],['achievement','🏆 Achievements'],['cosmetic','🎨 Cosmetic Pricing']].map(([id,l])=>`<button class="ghost ${state.adminCatalogTab0238===id?'active':''}" data-admin-main-0238="${id}">${l}</button>`).join('');
const headers=[...management.querySelectorAll('.section-title')],defs=[['chore','Chores'],['reward','Rewards'],['achievement','Achievements'],['cosmetic','Cosmetic Shop Pricing']];defs.forEach(([id,label])=>{const h=headers.find(x=>sectionLabel(x)===label),list=h?.nextElementSibling;if(h){const show=state.adminCatalogTab0238===id;h.hidden=!show;h.style.setProperty('display',show?'flex':'none','important');if(list){list.hidden=!show;list.style.setProperty('display',show?'':'none','important')}}});const actions=[...management.children].find(x=>x.classList?.contains('action-row'));if(actions){[...actions.children].forEach(b=>{const t=b.dataset.type;b.style.display=(t==='chore'&&state.adminCatalogTab0238==='chore')||(t==='achievement'&&state.adminCatalogTab0238==='achievement')?'':'none'})}
management.querySelectorAll('.admin-subtabs-0238').forEach(x=>x.remove());if(state.adminCatalogTab0238==='chore'){const h=headers.find(x=>sectionLabel(x)==='Chores'),list=h?.nextElementSibling;if(h&&list){const sub=document.createElement('div');sub.className='tabs admin-subtabs-0238';sub.innerHTML=['Daily','Weekly','Monthly','Seasonal'].map(x=>`<button class="ghost ${state.adminChoreSubtab0238===x?'active':''}" data-admin-chore-sub-0238="${x}">${x}</button>`).join('');h.after(sub);[...list.children].forEach(row=>row.hidden=!(row.textContent||'').toLowerCase().includes(state.adminChoreSubtab0238.toLowerCase()))}}
if(state.adminCatalogTab0238==='achievement'){const h=headers.find(x=>sectionLabel(x)==='Achievements'),list=h?.nextElementSibling;if(h&&list){const sub=document.createElement('div');sub.className='tabs admin-subtabs-0238';sub.innerHTML=['Visible','Secret'].map(x=>`<button class="ghost ${state.adminAchievementSubtab0238===x?'active':''}" data-admin-ach-sub-0238="${x}">${x}</button>`).join('');h.after(sub);[...list.children].forEach(row=>{const secret=(row.textContent||'').toLowerCase().includes('secret');row.hidden=state.adminAchievementSubtab0238==='Secret'?!secret:secret})}}
}
function profileControls(){if(state.view!=='profiles')return;const hero=document.querySelector('.fq-player-shell,.profile-page-hero');if(!hero)return;const back=hero.querySelector('[data-action="profile-back"]'),custom=hero.querySelector('[data-action="profile-open"]'),name=hero.querySelector('h2');if(!name||(!back&&!custom))return;let bar=hero.querySelector('.profile-title-control-row');if(!bar){bar=document.createElement('div');bar.className='profile-title-control-row';name.parentElement.insertBefore(bar,name);if(back)bar.append(back);bar.append(name);if(custom)bar.append(custom)}}
const oldRender=render;render=function(){oldRender();queueMicrotask(()=>{adminTabs();profileControls();badge()})};document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.adminMain0238){e.preventDefault();e.stopImmediatePropagation();state.adminCatalogTab0238=b.dataset.adminMain0238;adminTabs()}else if(b.dataset.adminChoreSub0238){e.preventDefault();e.stopImmediatePropagation();state.adminChoreSubtab0238=b.dataset.adminChoreSub0238;adminTabs()}else if(b.dataset.adminAchSub0238){e.preventDefault();e.stopImmediatePropagation();state.adminAchievementSubtab0238=b.dataset.adminAchSub0238;adminTabs()}},true);
badge();window.addEventListener('load',()=>{badge();setTimeout(()=>{badge();adminTabs();profileControls()},250)});
})();