/* Family Quest v0.23.11.0 — private Personal Goals */
(function(){
 state.personalQuests=state.personalQuests||[];state.personalQuestCompletions=state.personalQuestCompletions||[];state.personalStepProgress=state.personalStepProgress||[];
 async function loadPersonalGoals(){
  if(!window.FQAuth?.realSession)return;
  const c=window.FQAuth.client,u=window.FQAuth.profile?.user_id;
  const [q,r,s]=await Promise.all([c.from('personal_quests').select('*').order('created_at',{ascending:false}),c.from('personal_quest_completions').select('*').order('completed_at',{ascending:false}),c.from('personal_quest_step_progress').select('*').order('updated_at',{ascending:false})]);
  if(!q.error)state.personalQuests=q.data||[];if(!r.error)state.personalQuestCompletions=r.data||[];if(!s.error)state.personalStepProgress=s.data||[];
 }
 function activeGoals(){return (state.personalQuests||[]).filter(q=>q.status==='active')}
 function weekKey(){const d=new Date(),t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));t.setUTCDate(t.getUTCDate()+4-(t.getUTCDay()||7));const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));return t.getUTCFullYear()+'-'+String(Math.ceil((((t-y)/86400000)+1)/7)).padStart(2,'0')}
 function todayKey(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
 function progress(q){const rows=(state.personalQuestCompletions||[]).filter(x=>x.quest_id===q.id);if(q.schedule_type==='weekly_target'){const n=rows.filter(x=>x.period_key.startsWith(weekKey())).length;return {n,target:q.weekly_target||1,label:n+' / '+(q.weekly_target||1)+' this week'}}const done=rows.some(x=>x.period_key===todayKey()||x.period_key==='once');return {n:done?1:0,target:1,label:done?(q.schedule_type==='one_time'?'✓ Completed':'✓ Completed Today'):'Ready for a quick win'}}
 function scheduleLabel(q){if(q.schedule_type==='daily')return 'Daily';if(q.schedule_type==='weekly_target')return (q.weekly_target||1)+'× per week';if(q.schedule_type==='days')return 'Selected days';return q.target_date?'By '+q.target_date:'One time'}

 function occurrenceKey(q){if(q.schedule_type==='one_time')return 'once';if(q.schedule_type==='weekly_target')return weekKey();return todayKey()}
 function priorProgress(q,key){return (state.personalStepProgress||[]).find(x=>x.quest_id===q.id&&x.period_key!==key&&!x.resolved&&x.checked_indexes?.length)}
 function currentStepProgress(q){const key=occurrenceKey(q);return (state.personalStepProgress||[]).find(x=>x.quest_id===q.id&&x.period_key===key)||{checked_indexes:[]}}
 async function openGoalDetail(id){
  const q=(state.personalQuests||[]).find(x=>x.id===id);if(!q)return;const key=occurrenceKey(q),cur=currentStepProgress(q),old=priorProgress(q,key);
  if(old&&!cur.id&&!sessionStorage.getItem('fqCarryChoice:'+q.id+':'+key)){showCarryPrompt(q,old,key);return}
  renderGoalDetail(q,key,cur);
 }
 function showCarryPrompt(q,old,key){let d=document.getElementById('personalCarryDialog');if(!d){d=document.createElement('dialog');d.id='personalCarryDialog';document.body.appendChild(d)}const n=old.checked_indexes.length,total=(q.steps||[]).length;d.innerHTML='<div class="dialog-form"><h2>You already made progress</h2><p>You knocked out <strong>'+n+' of '+total+' steps</strong>. Want to keep going?</p><div class="dialog-actions"><button class="primary" data-action="personal-carry" data-id="'+q.id+'" data-old="'+old.period_key+'" data-key="'+key+'">⚡ Keep Going — '+n+'/'+total+'</button><button class="ghost" data-action="personal-fresh" data-id="'+q.id+'" data-key="'+key+'">↻ Start Fresh Today</button></div></div>';d.showModal()}
 function renderGoalDetail(q,key,cur){let d=document.getElementById('personalDetailDialog');if(!d){d=document.createElement('dialog');d.id='personalDetailDialog';document.body.appendChild(d)}const checked=cur.checked_indexes||[],steps=q.steps||[];d.innerHTML='<div class="dialog-form"><div class="section-title"><div><div class="kicker">JUST START</div><h2>'+esc(q.title)+'</h2></div><button class="ghost" data-action="personal-detail-close">Close</button></div>'+(steps.length?'<p class="muted">Pick the next small thing. Your progress saves automatically.</p><div class="simple-list">'+steps.map((s,i)=>'<label class="simple-item row"><input type="checkbox" data-action="personal-step" data-id="'+q.id+'" data-key="'+key+'" data-index="'+i+'" '+(checked.includes(i)?'checked':'')+'><span class="'+(checked.includes(i)?'done':'')+'">'+esc(typeof s==='string'?s:s.text)+'</span></label>').join('')+'</div><p><strong>'+checked.length+' of '+steps.length+' steps done</strong></p>':'<p class="muted">No steps added yet. You can still complete the goal when you are done.</p>')+'<button class="primary wide" data-action="personal-goal-complete" data-id="'+q.id+'" data-key="'+key+'">✓ Complete Goal</button></div>';d.showModal()}
 async function completeGoal(id,key){const {error}=await window.FQAuth.client.rpc('complete_personal_quest',{p_quest_id:id});if(error)return toast(error.message);if(key)await window.FQAuth.client.rpc('resolve_personal_quest_step_progress',{p_quest_id:id,p_period_key:key});await loadPersonalGoals();document.getElementById('personalDetailDialog')?.close();toast('✓ Completed! Nice work.');renderGoals()}
 function injectQuestMode(){if(state.view!=='chores'||document.querySelector('.fq-quest-mode'))return;const root=document.getElementById('view');if(!root)return;root.insertAdjacentHTML('afterbegin','<div class="segmented fq-quest-mode"><button class="active" data-action="quest-mode-household">Household Quests</button><button data-action="quest-mode-personal">Personal Goals</button></div>')}

 function homeCard(){
  const goals=activeGoals(),done=goals.reduce((n,q)=>n+(progress(q).n>=progress(q).target?1:0),0),best=goals.reduce((m,q)=>Math.max(m,q.current_streak||0),0);
  return '<div class="card fq-personal-home" data-action="personal-goals-open"><div class="section-title"><h3>🎯 Personal Momentum</h3><span class="chip">'+goals.length+' active</span></div><div class="row"><strong>'+done+' goals on target</strong><span>🔥 '+best+' momentum</span></div><p class="muted">Private goals · Tap to check in</p></div>';
 }
 function injectHome(){if(state.view!=='home')return;const root=document.getElementById('view');if(!root||root.querySelector('.fq-personal-home'))return;root.insertAdjacentHTML('beforeend',homeCard())}
 function renderGoals(){
  setHeader('PERSONAL GOALS','My Momentum');const goals=activeGoals();
  view.innerHTML='<div class="card"><div class="section-title"><div><h3>🎯 Personal Goals</h3><p class="muted">Private commitments to yourself. No penalties, no household overdue status.</p></div><button class="primary" data-action="personal-goal-new">+ New Goal</button></div></div><div class="grid two" style="margin-top:16px">'+goals.map(q=>{const p=progress(q);return '<div class="card"><div class="section-title"><div><h3>'+esc(q.title)+'</h3><span class="muted">'+scheduleLabel(q)+'</span></div><span class="chip">🔥 '+(q.current_streak||0)+'</span></div>'+(q.notes?'<p>'+esc(q.notes)+'</p>':'')+'<div class="xpbar"><i style="width:'+Math.min(100,(p.n/p.target)*100)+'%"></i></div><p class="'+(p.n>=p.target?'fq-goal-done':'muted')+'">'+p.label+' · Best '+(q.best_streak||0)+' · '+(q.total_completions||0)+' total</p><div class="action-row"><button class="primary" data-action="personal-goal-complete" data-id="'+q.id+'">✓ Complete</button><button class="ghost" data-action="personal-goal-start" data-id="'+q.id+'">⚡ Just Start</button><button class="ghost" data-action="personal-goal-edit" data-id="'+q.id+'">Edit</button>'+(q.total_completions>=7?'<button class="ghost" data-action="personal-goal-xp" data-id="'+q.id+'">⭐ Submit XP</button>':'')+'<button class="ghost" data-action="personal-goal-pause" data-id="'+q.id+'">Pause</button></div></div>'}).join('')+'</div>'+(goals.length?'':'<div class="card empty" style="margin-top:16px">No personal goals yet. Start with something small enough to win.</div>');
 }
 function openNew(editId){
  const q=editId?(state.personalQuests||[]).find(x=>x.id===editId):null;
  let d=document.getElementById('personalGoalDialog');if(!d){d=document.createElement('dialog');d.id='personalGoalDialog';d.innerHTML='<form id="personalGoalForm" class="dialog-form"><h2>🎯 Personal Goal</h2><input type="hidden" id="pgId"><label>Goal<input id="pgTitle" maxlength="120" required placeholder="Read for 20 minutes"></label><label>Notes<textarea id="pgNotes" rows="3" placeholder="What does success look like?"></textarea></label><label>Schedule<select id="pgSchedule"><option value="one_time">One time</option><option value="daily">Daily</option><option value="days">Specific days</option><option value="weekly_target">Times per week</option></select></label><label id="pgTargetWrap">Times per week<input id="pgTarget" type="number" min="1" max="14" value="3"></label><label id="pgDaysWrap">Days (comma separated: 0=Sun … 6=Sat)<input id="pgDays" placeholder="1,3,5"></label><label>Target / deadline<input id="pgDate" type="date"></label><label>Reminder<input id="pgReminder" type="time"></label><label>Steps — one per line<textarea id="pgSteps" rows="4" placeholder="Put shoes on\nWalk 10 minutes"></textarea></label><div class="dialog-actions"><button type="button" class="ghost" data-action="personal-goal-cancel">Cancel</button><button class="primary" type="submit">Save Goal</button></div></form>';document.body.appendChild(d);d.querySelector('#pgSchedule').addEventListener('change',goalFormVisibility);d.querySelector('#personalGoalForm').addEventListener('submit',saveGoal);}
  document.getElementById('pgId').value=q?.id||'';document.getElementById('pgTitle').value=q?.title||'';document.getElementById('pgNotes').value=q?.notes||'';document.getElementById('pgSchedule').value=q?.schedule_type||'daily';document.getElementById('pgTarget').value=q?.weekly_target||3;document.getElementById('pgDays').value=(q?.days_of_week||[]).join(',');document.getElementById('pgDate').value=q?.target_date||'';document.getElementById('pgReminder').value=q?.reminder_time?.slice(0,5)||'';document.getElementById('pgSteps').value=(q?.steps||[]).map(x=>typeof x==='string'?x:x.text).join('\n');goalFormVisibility();d.showModal();
 }
 function goalFormVisibility(){const v=document.getElementById('pgSchedule')?.value;document.getElementById('pgTargetWrap').style.display=v==='weekly_target'?'':'none';document.getElementById('pgDaysWrap').style.display=v==='days'?'':'none'}
 async function saveGoal(e){e.preventDefault();const id=document.getElementById('pgId').value,schedule_type=document.getElementById('pgSchedule').value,payload={title:document.getElementById('pgTitle').value.trim(),notes:document.getElementById('pgNotes').value.trim()||null,schedule_type,weekly_target:schedule_type==='weekly_target'?Number(document.getElementById('pgTarget').value||1):null,days_of_week:schedule_type==='days'?document.getElementById('pgDays').value.split(',').map(Number).filter(n=>n>=0&&n<=6):[],target_date:document.getElementById('pgDate').value||null,reminder_time:document.getElementById('pgReminder').value||null,reminder_enabled:!!document.getElementById('pgReminder').value,steps:document.getElementById('pgSteps').value.split('\n').map(x=>x.trim()).filter(Boolean)};let r;if(id)r=await window.FQAuth.client.from('personal_quests').update(payload).eq('id',id);else r=await window.FQAuth.client.from('personal_quests').insert({...payload,household_id:window.FQAuth.profile.household_id,user_id:window.FQAuth.profile.user_id});if(r.error)return toast(r.error.message);document.getElementById('personalGoalDialog').close();await loadPersonalGoals();renderGoals()}

 async function injectAdminClaims(){if(state.view!=='admin'||!isAdmin()||document.querySelector('.fq-personal-claims'))return;const {data,error}=await window.FQAuth.client.from('personal_quest_xp_claims').select('id,user_id,milestone,suggested_xp,status,created_at').eq('status','pending').order('created_at',{ascending:true});if(error||!data?.length)return;const users=new Map((state.users||[]).map(u=>[String(u.id),u.name]));const card=document.createElement('div');card.className='card admin-section fq-personal-claims';card.innerHTML='<div class="section-title"><h3>🎯 Personal Goal XP</h3><span class="chip">'+data.length+'</span></div><p class="muted">Private goal details stay private. Review only the consistency milestone and suggested award.</p><div class="simple-list">'+data.map(x=>'<div class="simple-item row"><div><h4>'+esc(users.get(String(x.user_id))||'Family Member')+'</h4><p>'+x.milestone+'-completion milestone · '+x.suggested_xp+' XP</p></div><div class="action-row"><button class="primary" data-action="personal-xp-review" data-id="'+x.id+'" data-decision="approved">Approve</button><button class="ghost" data-action="personal-xp-review" data-id="'+x.id+'" data-decision="denied">Decline</button></div></div>').join('')+'</div>';const host=document.querySelector('#view .admin-section')?.parentElement||document.getElementById('view');host.prepend(card)}
 document.addEventListener('click',async e=>{
  const b=e.target.closest?.('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
  if(a==='personal-xp-review'){const {error}=await window.FQAuth.client.rpc('review_personal_quest_xp',{p_claim_id:id,p_decision:b.dataset.decision});if(error)return toast(error.message);toast(b.dataset.decision==='approved'?'Personal Goal XP approved.':'Personal Goal XP declined.');document.querySelector('.fq-personal-claims')?.remove();await Promise.allSettled([loadPersonalGoals(),window.FQLoaders?.currentStats?.()]);injectAdminClaims();return}
  if(a==='personal-goals-open'){state.view='personal-goals';renderGoals();return}
  if(a==='personal-goal-new'){openNew();return}if(a==='personal-goal-edit'){openNew(id);return}if(a==='personal-goal-cancel'){document.getElementById('personalGoalDialog')?.close();return}if(a==='quest-mode-personal'){state.view='personal-goals';renderGoals();return}if(a==='quest-mode-household'){state.view='chores';render();return}if(a==='personal-goal-start'){openGoalDetail(id);return}if(a==='personal-detail-close'){document.getElementById('personalDetailDialog')?.close();return}
  if(a==='personal-carry'){const q=(state.personalQuests||[]).find(x=>x.id===id),old=(state.personalStepProgress||[]).find(x=>x.quest_id===id&&x.period_key===b.dataset.old);await window.FQAuth.client.rpc('save_personal_quest_step_progress',{p_quest_id:id,p_period_key:b.dataset.key,p_checked:old?.checked_indexes||[],p_carried_from:b.dataset.old});sessionStorage.setItem('fqCarryChoice:'+id+':'+b.dataset.key,'carry');document.getElementById('personalCarryDialog')?.close();await loadPersonalGoals();openGoalDetail(id);return}
  if(a==='personal-fresh'){await window.FQAuth.client.rpc('save_personal_quest_step_progress',{p_quest_id:id,p_period_key:b.dataset.key,p_checked:[],p_carried_from:null});sessionStorage.setItem('fqCarryChoice:'+id+':'+b.dataset.key,'fresh');document.getElementById('personalCarryDialog')?.close();await loadPersonalGoals();openGoalDetail(id);return}
  if(a==='personal-step'){const q=(state.personalQuests||[]).find(x=>x.id===id),cur=currentStepProgress(q),arr=new Set(cur.checked_indexes||[]),i=Number(b.dataset.index);b.checked?arr.add(i):arr.delete(i);const checked=[...arr].sort((x,y)=>x-y);await window.FQAuth.client.rpc('save_personal_quest_step_progress',{p_quest_id:id,p_period_key:b.dataset.key,p_checked:checked,p_carried_from:null});await loadPersonalGoals();if((q.steps||[]).length&&checked.length===(q.steps||[]).length){await completeGoal(id,b.dataset.key)}else renderGoalDetail(q,b.dataset.key,currentStepProgress(q));return}
  if(a==='personal-goal-complete'){await completeGoal(id,b.dataset.key||occurrenceKey((state.personalQuests||[]).find(x=>x.id===id)));return}
  if(a==='personal-goal-pause'){await window.FQAuth.client.from('personal_quests').update({status:'paused'}).eq('id',id);await loadPersonalGoals();renderGoals();return}
  if(a==='personal-goal-xp'){const {error}=await window.FQAuth.client.rpc('submit_personal_quest_xp',{p_quest_id:id});if(error)return toast(error.message);toast('XP milestone sent to Admin for approval.');return}
 },true);
 const prior=render;render=function(){if(state.view==='personal-goals'){renderGoals();return}prior();queueMicrotask(()=>{injectHome();injectQuestMode();injectAdminClaims()});if(state.view==='admin')setTimeout(injectAdminClaims,300)};
 window.FQLoaders=window.FQLoaders||{};window.FQLoaders.personalGoals=loadPersonalGoals;
 window.addEventListener('load',()=>setTimeout(()=>loadPersonalGoals().then(()=>{if(state.view==='home')injectHome()}),650));
})();