/* Family Quest v0.23.1 — immersive profiles */
(function(){
const oldProfileRender=renderProfiles;state.profileTab=state.profileTab==='overview'?'trophies':(state.profileTab||'trophies');
function themeMotif(u){const f=(u.frameId||'').toLowerCase();if(/autumn|harvest|thanksgiving|leaf/.test(f))return '🍂';if(/winter|ice|frost/.test(f))return '❄️';if(/gold|reward/.test(f))return '🪙';if(/grass|fresh-cut/.test(f))return '🌿';if(/laundry|bubble/.test(f))return '🫧';if(/sun|rainbow/.test(f))return '☀️';if(/chaos/.test(f))return '✨';return '◆'}
function deco(u){const m=themeMotif(u);return `<div class="profile-decor"><span class="d1">${m}</span><span class="d2">${m}</span><span class="d3">${m}</span><span class="d4">${m}</span></div>`}
function earnedAchievements(u){return state.achievements.filter(a=>(a.unlockedBy||[]).includes(u.name))}
function ownedCosmetics(u){const ids=new Set([u.spriteId,u.frameId,u.backgroundId,u.confettiId,...(u.cosmeticUnlocks||[]).map(x=>typeof x==='string'?x:x?.id)].filter(Boolean));return [...ids].map(cosmeticById).filter(Boolean)}
function xpInfo(u){const level=levelOf(u),within=((+u.xp||0)%1000),need=1000,pct=Math.max(0,Math.min(100,within/need*100));return {level,within,need,pct}}
function tabButton(id,label,icon){return `<button class="ghost ${state.profileTab===id?'active':''}" data-action="profile-tab" data-tab="${id}"><span class="tab-motif">${icon}</span>${label}</button>`}
function trophies(u){const a=earnedAchievements(u);return `<div class="fq-trophy-grid">${a.map(x=>`<div class="fq-trophy"><div class="icon">${x.icon||'🏆'}</div><strong>${esc(x.title)}</strong><p>${esc(x.desc||'Achievement unlocked')}</p></div>`).join('')||'<div class="empty">No claimed achievements yet.</div>'}</div>`}
function collection(u){const mine=u.name===state.currentUser,all=ownedCosmetics(u);return `<div class="fq-collection-grid">${all.map(x=>{const type=String(x.type||x.cosmetic_type||'avatar').toLowerCase(),isFx=type==='confetti';return `<div class="fq-collectible"><div class="cosmetic-preview">${cosmeticPreview(x)}</div><strong>${esc(x.name)}</strong><div class="muted">${esc(cosmeticTypeLabel(type))}</div>${mine&&isFx?`<div class="fq-preview-actions"><button class="ghost" data-action="profile-confetti-fall" data-cosmetic="${esc(x.id)}">🌧️ Preview Fall</button><button class="ghost" data-action="profile-confetti-burst" data-cosmetic="${esc(x.id)}">💥 Preview Burst</button></div>`:''}</div>`}).join('')||'<div class="empty">No earned cosmetics yet.</div>'}</div>`}
function stats(u){const approved=state.chores.reduce((n,c)=>n+(c.approvedCompletions||[]).filter(x=>String(x.completed_by)===String(u.id)).length,0),ach=earnedAchievements(u).length,cos=ownedCosmetics(u).length;return `<div class="fq-stat-list"><div class="fq-stat-row"><span class="muted">Approved Quests Loaded</span><strong>${approved}</strong><small>Current loaded quest history</small></div><div class="fq-stat-row"><span class="muted">Best Streak</span><strong>${u.bestStreak||0} days</strong><small>Personal best</small></div><div class="fq-stat-row"><span class="muted">Achievements</span><strong>${ach}</strong><small>Claimed trophies</small></div><div class="fq-stat-row"><span class="muted">Collection</span><strong>${cos}</strong><small>Unlocked/equipped cosmetics</small></div></div>`}
function player(){const u=state.users.find(x=>String(x.id)===String(state.profilePlayerId));if(!u){oldProfileRender();return}setHeader('PLAYER PROFILE',u.name);const a=earnedAchievements(u),xp=xpInfo(u),tab=state.profileTab||'trophies';state.profileTab=tab;const content=tab==='collection'?collection(u):tab==='stats'?stats(u):trophies(u),motif=themeMotif(u);view.innerHTML=`<div class="fq-player-shell bg-${esc(u.backgroundId||'plain-background')} frame-${esc(u.frameId||'plain-frame')}">${deco(u)}<button class="ghost fq-profile-back" data-action="profile-back">← Profiles</button>${u.name===state.currentUser?'<button class="primary fq-profile-customize" data-action="profile-open">Customize</button>':''}<div class="fq-profile-head">${cosmeticShowcaseMarkup(u)}<h2>${esc(u.name)}</h2><div class="profile-title">${esc(u.title||'Family Quester')}</div><div class="fq-xp"><div class="row" style="justify-content:center"><span class="chip">LEVEL ${xp.level}</span></div><div class="fq-xp-track"><div class="fq-xp-fill" style="width:${xp.pct}%"></div></div><div class="fq-xp-copy">${xp.within.toLocaleString()} / ${xp.need.toLocaleString()} XP toward next level</div></div><div class="fq-profile-stats"><div class="fq-stat"><span>💎 RP</span><strong>${(+u.rp||0).toLocaleString()}</strong></div><div class="fq-stat"><span>🔥 Streak</span><strong>${u.streak||0}</strong></div><div class="fq-stat"><span>🏆 Achievements</span><strong>${a.length}</strong></div><div class="fq-stat"><span>🎨 Collection</span><strong>${ownedCosmetics(u).length}</strong></div></div></div><div class="fq-profile-tabs">${tabButton('trophies','Trophy Case',motif)}${tabButton('collection','Collection',motif)}${tabButton('stats','Quest Stats',motif)}</div><div class="fq-profile-content">${content}</div></div>`}
function fxChars(id){const s=String(id||'').toLowerCase();if(/leaf|autumn/.test(s))return ['🍂','🍁','🍃'];if(/snow|winter|ice/.test(s))return ['❄️','✦','❅'];if(/coin|gold/.test(s))return ['●','🪙','✦'];if(/bubble|laundry/.test(s))return ['○','◌','🫧'];if(/grass/.test(s))return ['🌿','•','🍃'];if(/firework|chaos/.test(s))return ['✦','★','✧'];if(/rainbow|sun/.test(s))return ['☀️','★','◆'];return ['◆','●','■']}
function previewBurst(btn,id){const r=btn.getBoundingClientRect(),chars=fxChars(id);for(let i=0;i<34;i++){const p=document.createElement('i'),ang=Math.random()*Math.PI*2,dist=55+Math.random()*120;p.className='quest-burst';p.textContent=chars[i%chars.length];p.style.left=r.left+r.width/2+'px';p.style.top=r.top+r.height/2+'px';p.style.setProperty('--dx',Math.cos(ang)*dist+'px');p.style.setProperty('--dy',Math.sin(ang)*dist+'px');document.body.appendChild(p);setTimeout(()=>p.remove(),950)}}
function previewFall(id){const chars=fxChars(id);for(let i=0;i<42;i++){const p=document.createElement('i');p.className='fq-fall-preview';p.textContent=chars[i%chars.length];p.style.left=Math.random()*100+'vw';p.style.animationDelay=Math.random()*.6+'s';p.style.animationDuration=(1.8+Math.random()*1.4)+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),3800)}}
const css=document.createElement('style');css.textContent='.fq-fall-preview{position:fixed;z-index:99999;top:-35px;pointer-events:none;font-style:normal;font-size:22px;animation:fqPreviewFall 2.6s linear forwards}@keyframes fqPreviewFall{to{transform:translateY(110vh) rotate(420deg);opacity:.2}}';document.head.appendChild(css);
const oldRP=renderProfiles;renderProfiles=function(){oldRP();document.querySelectorAll('[data-action="profile-view"]').forEach(b=>{b.textContent='View Player Profile'})};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='profile-view'){e.preventDefault();e.stopImmediatePropagation();state.profilePlayerId=b.dataset.user;state.profileTab='trophies';player()}else if(b.dataset.action==='profile-tab'&&state.profilePlayerId){e.preventDefault();e.stopImmediatePropagation();state.profileTab=b.dataset.tab;player()}else if(b.dataset.action==='profile-back'&&state.profilePlayerId){e.preventDefault();e.stopImmediatePropagation();state.profilePlayerId=null;oldProfileRender()}else if(b.dataset.action==='profile-confetti-burst'){e.preventDefault();e.stopImmediatePropagation();previewBurst(b,b.dataset.cosmetic)}else if(b.dataset.action==='profile-confetti-fall'){e.preventDefault();e.stopImmediatePropagation();previewFall(b.dataset.cosmetic)}},true);
})();