/* Family Quest v0.23.11.0 — private Personal Goals */
(function(){
 state.personalQuests=state.personalQuests||[];state.personalQuestCompletions=state.personalQuestCompletions||[];
 async function loadPersonalGoals(){
  if(!window.FQAuth?.realSession)return;
  const c=window.FQAuth.client,u=window.FQAuth.profile?.user_id;
  const [q,r]=await Promise.all([c.from('personal_quests').select('*').order('created_at',{ascending:false}),c.from('personal_quest_completions').select('*').order('completed_at',{ascending:false})]);
  if(!q.error)state.personalQuests=q.data||[];if(!r.error)state.personalQuestCompletions=r.data||[];
 }
 function activeGoals(){return (state.personalQuests||[]).filter(q=>q.status==='active')}
 function weekKey(){const d=new Date(),t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));t.setUTCDate(t.getUTCDate()+4-(t.getUTCDay()||7));const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));return t.getUTCFullYear()+'-'+String(Math.ceil((((t-y)/86400000)+1)/7)).padStart(2,'0')}
 function todayKey(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
 function progress(q){const rows=(state.personalQuestCompletions||[]).filter(x=>x.quest_id===q.id);if(q.schedule_type==='weekly_target'){const n=rows.filter(x=>x.period_key.startsWith(weekKey())).length;return {n,target:q.weekly_target||1,label:n+' / '+(q.weekly_target||1)+' this week'}}const done=rows.some(x=>x.period_key===todayKey()||x.period_key==='once');return {n:done?1:0,target:1,label:done?'Done today':'Ready for a quick win'}}
 function scheduleLabel(q){if(q.schedule_type==='daily')return 'Daily';if(q.schedule_type==='weekly_target')return (q.weekly_target||1)+'× per week';if(q.schedule_type==='days')return 'Selected days';return q.target_date?'By '+q.target_date:'One time'}
 function homeCard(){
  const goals=activeGoals(),done=goals.reduce((n,q)=>n+(progress(q).n>=progress(q).target?1:0),0),best=goals.reduce((m,q)=>Math.max(m,q.current_streak||0),0);
  return '<div class="card fq-personal-home" data-action="personal-goals-open"><div class="section-title"><h3>🎯 Personal Momentum</h3><span class="chip">'+goals.length+' active</span></div><div class="row"><strong>'+done+' goals on target</strong><span>🔥 '+best+' momentum</span></div><p class="muted">Private goals · Tap to check in</p></div>';
 }
 function injectHome(){if(state.view!=='home')return;const root=document.getElementById('view');if(!root||root.querySelector('.fq-personal-home'))return;root.insertAdjacentHTML('beforeend',homeCard())}
 function renderGoals(){
  setHeader('PERSONAL GOALS','My Momentum');const goals=activeGoals();
  view.innerHTML='<div class="card"><div class="section-title"><div><h3>🎯 Personal Goals</h3><p class="muted">Private commitments to yourself. No penalties, no household overdue status.</p></div><button class="primary" data-action="personal-goal-new">+ New Goal</button></div></div><div class="grid two" style="margin-top:16px">'+goals.map(q=>{const p=progress(q);return '<div class="card"><div class="section-title"><div><h3>'+esc(q.title)+'</h3><span class="muted">'+scheduleLabel(q)+'</span></div><span class="chip">🔥 '+(q.current_streak||0)+'</span></div>'+(q.notes?'<p>'+esc(q.notes)+'</p>':'')+'<div class="xpbar"><i style="width:'+Math.min(100,(p.n/p.target)*100)+'%"></i></div><p class="muted">'+p.label+' · Best '+(q.best_streak||0)+' · '+(q.total_completions||0)+' total</p><div class="action-row"><button class="primary" data-action="personal-goal-complete" data-id="'+q.id+'">✓ Check In</button><button class="ghost" data-action="personal-goal-start" data-id="'+q.id+'">⚡ Just Start</button><button class="ghost" data-action="personal-goal-edit" data-id="'+q.id+'">Edit</button>'+(q.total_completions>=7?'<button class="ghost" data-action="personal-goal-xp" data-id="'+q.id+'">⭐ Submit XP</button>':'')+'<button class="ghost" data-action="personal-goal-pause" data-id="'+q.id+'">Pause</button></div></div>'}).join('')+'</div>'+(goals.length?'':'<div class="card empty" style="margin-top:16px">No personal goals yet. Start with something small enough to win.</div>');
 }
 function openNew(editId){
  const q=editId?(state.personalQuests||[]).find(x=>x.id===editId):null;
  let d=document.getElementById('personalGoalDialog');if(!d){d=document.createElement('dialog');d.id='personalGoalDialog';d.innerHTML='<form id="personalGoalForm" class="dialog-form"><h2>🎯 Personal Goal</h2><input type="hidden" id="pgId"><label>Goal<input id="pgTitle" maxlength="120" required placeholder="Read for 20 minutes"></label><label>Notes<textarea id="pgNotes" rows="3" placeholder="What does success look like?"></textarea></label><label>Schedule<select id="pgSchedule"><option value="one_time">One time</option><option value="daily">Daily</option><option value="days">Specific days</option><option value="weekly_target">Times per week</option></select></label><label id="pgTargetWrap">Times per week<input id="pgTarget" type="number" min="1" max="14" value="3"></label><label id="pgDaysWrap">Days (comma separated: 0=Sun … 6=Sat)<input id="pgDays" placeholder="1,3,5"></label><label>Target / deadline<input id="pgDate" type="date"></label><label>Reminder<input id="pgReminder" type="time"></label><label>Steps — one per line<textarea id="pgSteps" rows="4" placeholder="Put shoes on\nWalk 10 minutes"></textarea></label><div class="dialog-actions"><button type="button" class="ghost" data-action="personal-goal-cancel">Cancel</button><button class="primary" type="submit">Save Goal</button></div></form>';document.body.appendChild(d);d.querySelector('#pgSchedule').addEventListener('change',goalFormVisibility);d.querySelector('#personalGoalForm').addEventListener('submit',saveGoal);}
  document.getElementById('pgId').value=q?.id||'';document.getElementById('pgTitle').value=q?.title||'';document.getElementById('pgNotes').value=q?.notes||'';document.getElementById('pgSchedule').value=q?.schedule_type||'daily';document.getElementById('pgTarget').value=q?.weekly_target||3;document.getElementById('pgDays').value=(q?.days_of_week||[]).join(',');document.getElementById('pgDate').value=q?.target_date||'';document.getElementById('pgReminder').value=q?.reminder_time?.slice(0,5)||'';document.getElementById('pgSteps').value=(q?.steps||[]).map(x=>typeof x==='string'?x:x.text).join('\n');goalFormVisibility();d.showModal();
 }
 function goalFormVisibility(){const v=document.getElementById('pgSchedule')?.value;document.getElementById('pgTargetWrap').style.display=v==='weekly_target'?'':'none';document.getElementById('pgDaysWrap').style.display=v==='days'?'':'none'}
 async function saveGoal(e){e.preventDefault();const id=document.getElementById('pgId').value,schedule_type=document.getElementById('pgSchedule').value,payload={title:document.getElementById('pgTitle').value.trim(),notes:document.getElementById('pgNotes').value.trim()||null,schedule_type,weekly_target:schedule_type==='weekly_target'?Number(document.getElementById('pgTarget').value||1):null,days_of_week:schedule_type==='days'?document.getElementById('pgDays').value.split(',').map(Number).filter(n=>n>=0&&n<=6):[],target_date:document.getElementById('pgDate').value||null,reminder_time:document.getElementById('pgReminder').value||null,reminder_enabled:!!document.getElementById('pgReminder').value,steps:document.getElementById('pgSteps').value.split('\n').map(x=>x.trim()).filter(Boolean)};let r;if(id)r=await window.FQAuth.client.from('personal_quests').update(payload).eq('id',id);else r=await window.FQAuth.client.from('personal_quests').insert({...payload,household_id:window.FQAuth.profile.household_id,user_id:window.FQAuth.profile.user_id});if(r.error)return toast(r.error.message);document.getElementById('personalGoalDialog').close();await loadPersonalGoals();renderGoals()}
 document.addEventListener('click',async e=>{
  const b=e.target.closest?.('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
  if(a==='personal-goals-open'){state.view='personal-goals';renderGoals();return}
  if(a==='personal-goal-new'){openNew();return}if(a==='personal-goal-edit'){openNew(id);return}if(a==='personal-goal-cancel'){document.getElementById('personalGoalDialog')?.close();return}if(a==='personal-goal-start'){toast('You started. That counts — pick one tiny step and keep going.');return}
  if(a==='personal-goal-complete'){const {error}=await window.FQAuth.client.rpc('complete_personal_quest',{p_quest_id:id});if(error)return toast(error.message);await loadPersonalGoals();toast('Nice. Momentum kept.');renderGoals();return}
  if(a==='personal-goal-pause'){await window.FQAuth.client.from('personal_quests').update({status:'paused'}).eq('id',id);await loadPersonalGoals();renderGoals();return}
  if(a==='personal-goal-xp'){const {error}=await window.FQAuth.client.rpc('submit_personal_quest_xp',{p_quest_id:id});if(error)return toast(error.message);toast('XP milestone sent to Admin for approval.');return}
 },true);
 const prior=render;render=function(){if(state.view==='personal-goals'){renderGoals();return}prior();queueMicrotask(injectHome)};
 window.FQLoaders=window.FQLoaders||{};window.FQLoaders.personalGoals=loadPersonalGoals;
 window.addEventListener('load',()=>setTimeout(()=>loadPersonalGoals().then(()=>{if(state.view==='home')injectHome()}),650));
})();